-- Neon-compatible dump for Game Warm-up
-- Generated from local DB warmup_library with: pg_dump --no-owner --no-acl
-- Cleaned: removed OWNER TO postgres, GRANT/ACL, \\restrict/\\unrestrict, transaction_timeout
-- Schema: public
-- Tables: contexts, purposes, games, game_contexts, game_purposes, reviews
-- Expected: 20 games, reviews preserved
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: contexts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contexts (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    slug character varying(80) NOT NULL
);


--
-- Name: contexts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contexts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contexts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_contexts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_contexts (
    game_id bigint NOT NULL,
    context_id bigint NOT NULL
);


--
-- Name: game_purposes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.game_purposes (
    game_id bigint NOT NULL,
    purpose_id bigint NOT NULL
);


--
-- Name: games; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.games (
    id bigint NOT NULL,
    context character varying(500),
    created_at timestamp(6) with time zone NOT NULL,
    description text NOT NULL,
    duration_max integer NOT NULL,
    duration_min integer NOT NULL,
    how_to_play text NOT NULL,
    max_players integer,
    min_players integer NOT NULL,
    name character varying(200) NOT NULL,
    name_search character varying(200) NOT NULL,
    preparation text,
    preparation_required boolean NOT NULL,
    preparation_time integer,
    purpose character varying(500),
    rules text,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purposes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purposes (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    slug character varying(80) NOT NULL
);


--
-- Name: purposes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.purposes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purposes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    comment character varying(1000) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    display_name character varying(80) NOT NULL,
    rating integer NOT NULL,
    game_id bigint NOT NULL
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: contexts; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.contexts (id, name, slug) FROM stdin;
9	Trong lớp học	classroom
10	Trong phòng	indoor
11	Ngoài trời	outdoor
12	Campus	campus
13	Nhóm nhỏ	small-group
\.


--
-- Data for Name: game_contexts; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.game_contexts (game_id, context_id) FROM stdin;
1	9
2	10
3	9
4	13
5	9
6	13
7	9
8	9
9	10
10	9
11	13
12	9
13	10
14	10
15	12
16	13
17	9
18	9
19	11
20	12
\.


--
-- Data for Name: game_purposes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.game_purposes (game_id, purpose_id) FROM stdin;
1	2
1	3
1	8
1	4
2	2
2	6
2	8
2	4
3	2
3	3
3	8
3	4
4	2
4	3
4	8
4	4
4	7
5	2
5	6
5	3
5	8
5	1
6	2
6	6
6	5
6	8
6	1
7	2
7	1
8	2
8	5
8	8
8	4
8	1
9	2
9	8
9	4
9	7
10	2
10	3
10	8
10	4
11	2
11	6
11	8
11	1
11	7
12	2
12	6
12	3
12	8
12	4
13	2
13	6
13	8
13	7
14	2
14	6
14	4
14	1
15	2
15	3
15	8
15	4
16	2
16	3
16	8
16	4
16	7
17	2
17	6
17	8
17	4
18	2
18	8
18	4
18	7
19	2
19	6
19	3
19	1
20	2
20	6
20	5
20	8
7	3
7	7
\.


--
-- Data for Name: games; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.games (id, context, created_at, description, duration_max, duration_min, how_to_play, max_players, min_players, name, name_search, preparation, preparation_required, preparation_time, purpose, rules, updated_at) FROM stdin;
1	Trong lớp học	2026-08-13 22:05:26.070313+07	Chinese Whisper bằng lời: thì thầm một câu ngắn lần lượt trong nhóm, rồi so câu cuối với câu gốc.	8	8	1. Cả nhóm đứng hoặc ngồi thành vòng trong lớp.\n2. Leader nghĩ một câu ngắn, dễ hiểu rồi thì thầm vào tai người bên cạnh.\n3. Lần lượt thì thầm đến người cuối. Người cuối nói to câu nhận được.\n4. Leader đọc câu gốc. Cả nhóm cười với chỗ “lạc” — không ai bị phạt.	5	5	Truyền tin nhắn	truyen tin nhan	Không cần chuẩn bị thân thể. Leader chỉ cần nghĩ sẵn 1 câu trung tính.	f	0	Khởi động trước khi họp nhóm, Phá băng, Tăng tương tác, Tạo tiếng cười	Chỉ dùng câu trung tính. Nói rõ, không cố tình phá nếu nhóm còn rụt rè.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.767546+07
2	Trong phòng	2026-08-13 22:05:26.074761+07	Mini Scavenger Hunt: mỗi người tìm nhanh một món đồ theo gợi ý rồi khoe với nhóm trong phòng.	18	18	1. Leader đọc lần lượt 4–5 gợi ý dễ: “một vật màu xanh”, “thứ làm bạn tỉnh táo”, “một món dùng lúc học”.\n2. Mỗi gợi ý: mọi người có 20–30 giây tìm đồ trong phòng / quanh chỗ ngồi.\n3. Lần lượt đưa đồ ra giữa nhóm và nói đúng một câu.\n4. Không ai bị loại. Ai chưa tìm thấy có thể mô tả món đồ.\n5. Leader chọn 1 món “đáng nhớ nhất” để cả nhóm vỗ tay, không chấm điểm.	5	5	Đi tìm báu vật trong nhà	di tim bau vat trong nha	Có hoạt động tay chân: cho 2–3 phút dọn góc ngồi. Leader soạn sẵn list gợi ý trước.	t	3	Khởi động trước khi họp nhóm, Phá băng, Tăng tương tác, Tạo sự thoải mái	Nhịp chậm. Không biến thành cuộc đua.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.79533+07
3	Trong lớp học	2026-08-13 22:05:26.076101+07	Leader ra lệnh, cả nhóm làm NGƯỢC: nghe “đứng” thì ngồi, nghe “ngồi” thì đứng.	5	5	1. Cả nhóm đứng tại chỗ trong lớp, chừa khoảng để ngồi xuống an toàn.\n2. Leader nói chậm: “Đứng lên” hoặc “Ngồi xuống”. Cả nhóm làm NGƯỢC lệnh.\n3. Sai thì cười và chơi tiếp, không bị loại.\n4. Kết thúc bằng một lệnh thật để cả nhóm ngồi lại.	10	10	Đứng lên - Ngồi xuống theo lệnh ngược	dung len - ngoi xuong theo lenh nguoc	Có hoạt động tay chân: dành 1–2 phút đứng dậy. Không chơi nếu ai đang không tiện đứng.	t	2	Khởi động trước khi họp nhóm, Phá băng, Tăng tương tác, Tạo tiếng cười	Nhịp chậm, không loại người.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.805642+07
4	Nhóm nhỏ	2026-08-13 22:05:26.077111+07	Ba người nối một câu chuyện rất ngắn: mở đầu, tình huống, kết. Người còn lại thêm chi tiết nhỏ.	10	10	1. Nhóm ngồi thành vòng nhỏ. Leader đưa chủ đề nhẹ: “một buổi học bị mất điện”.\n2. Người 1 nói 2–3 câu mở đầu. Người 2 thêm tình huống. Người 3 kết thúc.\n3. Người còn lại thêm đúng 1 câu chi tiết nhỏ.\n4. Không cần hay. Chỉ cần nối được mạch.	4	4	Câu chuyện 3 chương	cau chuyen 3 chuong	Không có hoạt động tay chân — không dành 5 phút chuẩn bị thân thể.	f	0	Giao tiếp, Khởi động trước khi họp nhóm, Phá băng, Tăng tương tác, Tạo tiếng cười	Không bắt bịa dài. Không chê ý tưởng.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.813532+07
5	Trong lớp học	2026-08-13 22:05:26.078423+07	Mỗi người chọn một biệt danh dễ gọi trong buổi họp mặt, giải thích bằng một câu.	7	7	1. Leader nêu ví dụ trước: “Hôm nay mình là Trà Đá, vì mình tỉnh táo chậm”.\n2. Lần lượt mỗi người nói: tên thật + biệt danh + lý do một câu.\n3. Biệt danh phải dễ nói, không đụng chạm ngoại hình / điểm yếu.\n4. Leader ghi nhanh lên bảng để mọi người nhớ.	5	5	Đặt biệt danh vui	dat biet danh vui	Không cần chuẩn bị trước. Ai không muốn biệt danh có thể dùng tên + một cử chỉ.	f	0	Khởi động trước khi họp nhóm, Làm quen, Phá băng, Tạo sự thoải mái, Tạo tiếng cười	Cấm biệt danh chế giễu.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.822956+07
6	Nhóm nhỏ	2026-08-13 22:05:26.080451+07	Cả nhóm tìm càng nhiều điểm chung càng tốt trong thời gian ngắn, không cần sâu.	8	8	1. Leader đặt câu dễ: “Ai từng thức khuya làm bài giơ tay”.\n2. Những người giơ tay nói thêm 1 chi tiết rất ngắn.\n3. Lặp 4–5 câu: đồ uống, môn học, thú cưng, ca sĩ nghe dạo này.\n4. Leader ghi 3 điểm chung lên bảng rồi cả nhóm bắt tay.	5	5	Tìm điểm chung nhanh	tim diem chung nhanh	Không cần chuẩn bị thân thể. Leader chỉ cần 4–5 câu hỏi đóng (có/không) soạn sẵn.	f	0	Khởi động trước khi họp nhóm, Làm quen, Phá băng, Tìm điểm chung, Tạo sự thoải mái	Không hỏi thu nhập, điểm số, chuyện gia đình nhạy cảm.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.831741+07
7	Trong lớp học	2026-08-13 22:05:26.081919+07	Mỗi người chọn một món đồ. Cả nhóm đoán món đó của ai, rồi chủ nhân nói một câu.	10	10	1. Mỗi người chọn một món gần tầm tay, đặt úp hoặc giấu tên.\n2. Lần lượt giơ đồ lên, chưa nói tên chủ nhân.\n3. Cả nhóm đoán chủ nhân. Chủ nhân xác nhận và nói 1 câu về món đồ.\n4. Không cần đoán đúng hết.	5	5	Đoán chủ nhân	doan chu nhan	Cho 1–2 phút chọn đồ trong lớp. Không dùng đồ mang tính riêng tư quá.	t	2	Giao tiếp, Làm quen, Phá băng, Tạo tiếng cười	Không tạo áp lực phải đoán đúng.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.839339+07
8	Trong lớp học	2026-08-13 22:05:26.082925+07	Mỗi ô bingo là một câu dễ. Tìm người trong lớp khớp và đánh dấu.	15	15	1. Leader phát bảng bingo 3x3 hoặc 4x4 đã in sẵn.\n2. Mỗi ô là một đặc điểm nhẹ: “hay nghe podcast”, “nấu được một món”, “thích mèo”.\n3. Đi quanh lớp, hỏi nhau. Ai khớp ký tên vào ô và kể đúng 1 câu.\n4. Ai có 1 hàng thì hô “Bingo” — cả nhóm vỗ tay, không tặng phạt.	12	12	Bingo làm quen	bingo lam quen	Leader phải chuẩn bị bảng bingo trước khi bắt đầu. Không thêm 5 phút khởi động thân thể.	t	10	Khởi động trước khi họp nhóm, Làm quen, Phá băng, Tìm điểm chung, Tăng tương tác	Ô phải dễ, phù hợp nhóm mới.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.847833+07
9	Trong phòng	2026-08-13 22:05:26.082925+07	Người trước nói một từ, người sau nói từ liên quan. Giữ nhịp chậm, không loại.	6	6	1. Hai người ngồi đối diện. Leader (hoặc một người) mở từ: “Nhóm”.\n2. Người kia nói một từ liên quan: “họp”, “bài tập”, “lớp”…\n3. Đi vài vòng. Nếu kẹt, được hỏi gợi ý: “nghĩ về đồ ăn / môn học”.\n4. Kết bằng từ cuối cùng nói đồng thanh.	2	2	Từ nối từ	tu noi tu	Không cần chuẩn bị trước. Có thể bắt đầu ngay.	f	0	Giao tiếp, Khởi động trước khi họp nhóm, Phá băng, Tăng tương tác	Không tính giờ gấp. Im lặng 5 giây vẫn được.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.854871+07
10	Trong lớp học	2026-08-13 22:05:26.083925+07	Leader chiếu hoặc giơ hình; nhóm đoán từ/cụm từ. Ưu tiên hình vui, không đánh đố.	10	10	1. Leader chuẩn bị 6–8 hình in sẵn hoặc viết trên bảng.\n2. Giơ từng hình 20–30 giây.\n3. Mọi người đoán nói to, không giành lời.\n4. Leader chốt đáp án rồi sang hình tiếp. Dừng khi hết giờ.	5	5	Nhìn hình đoán chữ	nhin hinh doan chu	Leader phải chuẩn bị hình trước. Tránh hình phản cảm hoặc quá khó.	t	10	Khởi động trước khi họp nhóm, Phá băng, Tăng tương tác, Tạo tiếng cười	Không xếp hạng ai đoán nhanh nhất.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.86226+07
11	Nhóm nhỏ	2026-08-13 22:05:26.085391+07	Mỗi người mô tả mình tuần này bằng đúng 3 từ, rồi giải thích 10 giây nếu muốn.	5	5	1. Leader làm mẫu: “Deadline – trà đá – mưa”.\n2. Mỗi người nói 3 từ. Có thể viết ra giấy rồi đọc.\n3. Không bắt kể dài. Ai ngại chỉ cần 3 từ, không giải thích.\n4. Leader gom điểm chung của cả nhóm.	5	5	Giới thiệu bằng 3 từ	gioi thieu bang 3 tu	Cho 20 giây nghĩ trước khi bắt đầu vòng nói.	f	0	Giao tiếp, Khởi động trước khi họp nhóm, Làm quen, Phá băng, Tạo sự thoải mái	Câu trả lời ba từ là đủ.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.869194+07
12	Trong lớp học	2026-08-13 22:05:26.086397+07	Chọn nhanh một trong hai thứ dễ: trà/cà phê, sáng/tối, mèo/chó… Không có đáp án đúng.	7	7	1. Leader đọc cặp: “Trà sữa hay nước lọc?”\n2. Mọi người giơ 1 ngón / 2 ngón, hoặc bước sang trái/phải trong lớp.\n3. Leader hỏi 1–2 người vì sao — trả lời một câu.\n4. Lặp 5–6 cặp đời thường, không chính trị, không ngoại hình.	8	8	This or That	this or that	Không cần chuẩn bị thân thể. Leader soạn sẵn 5–6 cặp lựa chọn dễ.	f	0	Khởi động trước khi họp nhóm, Phá băng, Tăng tương tác, Tạo sự thoải mái, Tạo tiếng cười	Không tranh luận ai đúng.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.87517+07
13	Trong phòng	2026-08-13 22:05:26.08762+07	Mỗi người chọn 1–2 biểu cảm hoặc sticker giấy để mô tả cảm xúc lúc bắt đầu buổi họp mặt.	4	4	1. Leader phát giấy nhỏ / sticky note. Mọi người vẽ một mặt cười hoặc viết 1 từ cảm xúc.\n2. Lần lượt giơ giấy lên. Muốn nói thêm một câu thì nói, không bắt buộc.\n3. Leader gom cảm xúc nhóm rồi chuyển sang việc chính, không phán xét.	5	5	Emoji tâm trạng	emoji tam trang	Không có hoạt động tay chân nặng — không thêm 5 phút chuẩn bị. Có thể dùng giấy sẵn trong phòng.	f	0	Giao tiếp, Khởi động trước khi họp nhóm, Phá băng, Tạo sự thoải mái	Không hỏi “vì sao buồn”.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.879714+07
14	Trong phòng	2026-08-13 22:05:26.088869+07	Khoe một vật trong tầm tay và nói tối đa 30 giây vì sao hôm nay để nó gần mình.	8	8	1. Cho 1 phút tìm vật (ly, tai nghe, vở, móc khóa).\n2. Mỗi người: giơ vật + nói tối đa 30 giây.\n3. Nhóm vỗ tay nhẹ. Không so sánh vật “cool” hơn.	5	5	Show and Tell 30 giây	show and tell 30 giay	Có thao tác cầm đồ: cho 1 phút tìm vật trong phòng.	t	1	Làm quen, Phá băng, Tăng tương tác, Tạo sự thoải mái	Leader canh giờ nhẹ, không cắt lời đột ngột.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.885337+07
15	Campus	2026-08-13 22:05:26.089878+07	Chọn một trong hai tình huống vô hại, giải thích đúng một câu. Chơi khi đang đi hoặc đứng trên campus.	7	7	1. Leader đọc: “Thức khuya làm bài hay dậy sớm làm bài?”\n2. Giơ tay hoặc bước sang hai phía.\n3. 1–2 người giải thích một câu.\n4. Lặp 4–5 câu. Câu cuối liên quan việc nhóm sắp làm.	5	5	Would You Rather nhẹ	would you rather nhe	Không cần chuẩn bị trước. Cấm tình huống sợ hãi, ngoại hình, tiền bạc.	f	0	Khởi động trước khi họp nhóm, Phá băng, Tăng tương tác, Tạo tiếng cười	Không có đáp án thắng.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.889807+07
16	Nhóm nhỏ	2026-08-13 22:05:26.090879+07	Mỗi người thêm đúng một câu vào câu chuyện chung, đi một vòng.	8	8	1. Leader mở: “Sáng nay một nhóm sinh viên vào lớp và thấy…”\n2. Mỗi người thêm 1 câu. Đi hết vòng, có thể vòng 2 nếu còn giờ.\n3. Ai kẹt được gợi ý: “thêm một chi tiết đồ vật / thời tiết”.\n4. Người cuối kết thúc có hậu.	5	5	Câu chuyện nối câu	cau chuyen noi cau	Không cần chuẩn bị thân thể. Nếu ngại, nói một câu rất ngắn như “rồi mất điện”.	f	0	Giao tiếp, Khởi động trước khi họp nhóm, Phá băng, Tăng tương tác, Tạo tiếng cười	Không được bỏ lượt.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.895295+07
17	Trong lớp học	2026-08-13 22:05:26.090879+07	Leader nêu chủ đề, ai khớp thì high-five người bên cạnh. Rất nhanh, rất ít nói.	4	4	1. Cả nhóm đứng thành vòng trong lớp.\n2. “High-five nếu hôm nay uống cà phê.” Ai khớp high-five người cạnh mình.\n3. Đổi chủ đề: ngủ muộn, thích mèo, đang mang balo.\n4. Làm 6–8 chủ đề. Chủ đề cuối: “High-five nếu sẵn sàng vào việc”.	10	10	High-five ảo theo chủ đề	high-five ao theo chu de	Phù hợp nhóm rụt rè vì gần như không phải nói. Không cần 5 phút chuẩn bị.	f	0	Khởi động trước khi họp nhóm, Phá băng, Tăng tương tác, Tạo sự thoải mái	Không bắt kể thêm. Chỉ chơi trực tiếp trong lớp.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.901219+07
18	Trong lớp học	2026-08-13 22:05:26.092376+07	Leader hỏi câu siêu dễ, mỗi người trả lời đúng một từ trong khoảng 3–5 giây.	5	5	1. Câu mẫu: “Đồ uống lúc này?”, “Môn đang tới hạn?”.\n2. Đi vòng quanh lớp. Không giải thích.\n3. 2–3 vòng câu khác nhau.\n4. Ai chưa nghĩ ra nói “nước lọc” / “chưa nghĩ” — vẫn tính là đã tham gia.	5	5	Câu hỏi 3 giây	cau hoi 3 giay	Không cần chuẩn bị trước. Câu phải trả lời được bằng một từ.	f	0	Giao tiếp, Khởi động trước khi họp nhóm, Phá băng, Tăng tương tác	Không biến thành thẩm vấn. Leader không comment đúng sai.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.90633+07
19	Ngoài trời	2026-08-13 22:05:26.092376+07	Chọn một con vật cho “version mình lúc họp nhóm” và nói lý do một câu. Chơi ngoài trời nếu tiện.	6	6	1. Leader mẫu: “Mình là mèo hôm nay, vì muốn ngồi im nghe trước”.\n2. Mỗi người chọn con vật. Không cần độc lạ.\n3. Nói 1 câu lý do. Leader ghi nhanh lên giấy.\n4. Không bắt chước tiếng kêu nếu ai ngại.	5	5	Con vật đại diện	con vat dai dien	Không cần chuẩn bị trước. Không gán con vật cho người khác.	f	0	Làm quen, Phá băng, Tạo sự thoải mái, Tạo tiếng cười	Không đùa theo hướng chế giễu.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.910164+07
20	Campus	2026-08-13 22:05:26.093395+07	Leader nêu 4 vibe; mỗi người chọn 1. Những người cùng vibe đứng lại gần nhau trên campus / hành lang.	5	5	1. Bốn vibe: “muốn nghe”, “muốn nói”, “muốn pha trò”, “muốn vào việc luôn”.\n2. Mỗi người chọn 1 (giơ số ngón tay).\n3. Cùng số thì bước lại gần và chào nhau. Không có vibe nào “đúng hơn”.\n4. Leader điều chỉnh cách họp mặt cho khớp năng lượng nhóm.	8	8	Tìm người cùng vibe	tim nguoi cung vibe	Không cần chuẩn bị trước. Giúp nhóm mới không bị ép phải nói nhiều.	f	0	Khởi động trước khi họp nhóm, Phá băng, Tìm điểm chung, Tạo sự thoải mái	Tôn trọng người chọn “muốn nghe”.\n\nQuy định chung:\n• Không ai được bỏ qua lượt. Nếu đang ngại, trả lời ngắn (một từ, một cử chỉ, hoặc “cho mình 5 giây”).\n• Không tạo áp lực cạnh tranh quá mạnh. Không tính điểm trừ, không xếp hạng thua.\n• Không đánh giá hoặc chê câu trả lời.\n• Ưu tiên câu hỏi dễ, đời thường, phù hợp nhóm mới làm quen.\n• Trò không có hoạt động tay chân thì không dành 5 phút chuẩn bị trước.\n• Trò cần tài liệu/hình ảnh (Bingo, Nhìn hình đoán chữ): Leader chuẩn bị nội dung trước khi bắt đầu.\n• Trò có hoạt động tay chân: cho mọi người vài phút đứng dậy / tìm đồ trước khi chơi.\n• Chỉ chơi trực tiếp trong cùng một không gian.	2026-08-13 22:23:29.914707+07
\.


--
-- Data for Name: purposes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.purposes (id, name, slug) FROM stdin;
1	Làm quen	meet
2	Phá băng	icebreak
3	Tạo tiếng cười	laugh
4	Tăng tương tác	interact
5	Tìm điểm chung	common
6	Tạo sự thoải mái	comfort
7	Giao tiếp	communicate
8	Khởi động trước khi họp nhóm	kickoff
\.


--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.reviews (id, comment, created_at, display_name, rating, game_id) FROM stdin;
1	thanh	2026-08-13 22:14:56.14541+07	thanh	1	7
2	Choi truc tiep trong lop rat nhe nhang.	2026-08-13 22:25:43.353318+07	Tester	5	8
\.


--
-- Name: contexts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.contexts_id_seq', 13, true);


--
-- Name: games_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.games_id_seq', 20, true);


--
-- Name: purposes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.purposes_id_seq', 8, true);


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reviews_id_seq', 2, true);


--
-- Name: contexts contexts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contexts
    ADD CONSTRAINT contexts_pkey PRIMARY KEY (id);


--
-- Name: game_contexts game_contexts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_contexts
    ADD CONSTRAINT game_contexts_pkey PRIMARY KEY (game_id, context_id);


--
-- Name: game_purposes game_purposes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_purposes
    ADD CONSTRAINT game_purposes_pkey PRIMARY KEY (game_id, purpose_id);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: purposes purposes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purposes
    ADD CONSTRAINT purposes_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: purposes uk26o5x2l35n517qv9fk02osowj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purposes
    ADD CONSTRAINT uk26o5x2l35n517qv9fk02osowj UNIQUE (slug);


--
-- Name: contexts ukljtxq7a7jng253drm2nwf0mhp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contexts
    ADD CONSTRAINT ukljtxq7a7jng253drm2nwf0mhp UNIQUE (slug);


--
-- Name: reviews fk1cmcqkmc8g630wpn52m1mv8re; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk1cmcqkmc8g630wpn52m1mv8re FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: game_contexts fk2b11xe8oqi86oh42kojetatvr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_contexts
    ADD CONSTRAINT fk2b11xe8oqi86oh42kojetatvr FOREIGN KEY (context_id) REFERENCES public.contexts(id);


--
-- Name: game_purposes fk338p34sgkla2t2d626aqcd8ju; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_purposes
    ADD CONSTRAINT fk338p34sgkla2t2d626aqcd8ju FOREIGN KEY (purpose_id) REFERENCES public.purposes(id);


--
-- Name: game_contexts fkc0i9hy1983aqysar1mdif7gp5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_contexts
    ADD CONSTRAINT fkc0i9hy1983aqysar1mdif7gp5 FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: game_purposes fktce0j0gw2iifhebv99pjjfbsf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.game_purposes
    ADD CONSTRAINT fktce0j0gw2iifhebv99pjjfbsf FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- PostgreSQL database dump complete
--



